### ISSUE TITLE
Allow support of collections without any items

### ISSUE THREAD

**Issue by lubojr** [eodash/eodash_catalog#3]
Allow support of generation (add visualization info and possibly others) of collections without any items without the need to "hack around" generating items for example such as:

```yaml
    Type: "OverwriteTimes"
    Times:
      - "2020-01-01"
    OverwriteBBox: [-31.900405,46.194904,27.042845,72.215738]
```
for WMS layers without time and investigate options for others
